#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/onedesk/onedesk /usr/bin/onedesk
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/onedesk.service ]; then
			rm /etc/systemd/system/onedesk.service /usr/lib/systemd/system/onedesk.service /usr/lib/systemd/user/onedesk.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/onedesk/files/systemd/onedesk.service /usr/lib/systemd/system/onedesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload onedesk.service: Unit onedesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/onedesk.service:10: Executable path is not absolute: pkill -f "onedesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/onedesk.service
		fi
		systemctl daemon-reload
		systemctl enable onedesk
		systemctl start onedesk
	fi
fi
